# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
[default.deploy]
[default.deploy.parameters]
stack_name = "CIB-CLOUDFRONT-MULTI-SPA-LAMBDA-EDGE"
#s3_bucket = "put bucket name if u have one for deployments"
region = "us-east-1" 
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
s3_prefix = "CIB-CLOUDFRONT-MULTI-SPA-LAMBDA-EDGE"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true


# [default.sync.parameters]
# watch = true

# [default.local_start_api.parameters]
# warm_containers = "EAGER"

# [default.local_start_lambda.parameters]
# warm_containers = "EAGER"
